FROM node:22
WORKDIR /app
COPY db.json .
RUN npm install -g json-server@0.17.4 nodemon@3.1.10
EXPOSE 3000
ENV CHOKIDAR_USEPOLLING=true CHOKIDAR_INTERVAL=500
CMD ["nodemon", "--legacy-watch", "--watch", "/app/db.json", "--exec", "json-server --watch /app/db.json --port 3000 --host 0.0.0.0"]