services:

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vinylstore-angular-container
    ports:
      - "8080:80"
    depends_on:
      - json-server-api


  json-server-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: vinylstore-json-server-container
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./db.json
        target: /app/db.json